import { positiveCategories, reviewCategories, warningCategories } from './types.js'

export { positiveCategories, reviewCategories, warningCategories }

export const categoryLabels = {
  GOOD_FOOD: 'Good food',
  GOOD_SERVICE: 'Good service',
  GOOD_VALUE: 'Good value',
  AUTHENTIC_LOCAL: 'Authentic local',
  BAD_FOOD: 'Food concerns',
  BAD_SERVICE: 'Service concerns',
  OVERPRICED: 'Overpriced mentions',
  TOURIST_TRAP: 'Tourist-trap mentions',
  HIDDEN_CHARGES: 'Unexpected charges',
  SERVICE_NOT_INCLUDED: 'Service fee mentions',
  SCAM_WARNING: 'Scam-like wording',
}

export const categoryDescriptions = {
  GOOD_FOOD: 'Reviews mention tasty, fresh, or well-prepared food.',
  GOOD_SERVICE: 'Reviews mention friendly, helpful, or fast service.',
  GOOD_VALUE: 'Reviews mention fair prices or good value.',
  AUTHENTIC_LOCAL: 'Reviews mention a local, traditional, or less touristy feel.',
  BAD_FOOD: 'Some reviews mention poor food quality.',
  BAD_SERVICE: 'Some reviews mention slow, rude, or unfriendly service.',
  OVERPRICED: 'Some reviews mention high prices or poor value.',
  TOURIST_TRAP: 'Some reviews describe tourist-trap-like patterns.',
  HIDDEN_CHARGES: 'Some visitors reported unexpected charges.',
  SERVICE_NOT_INCLUDED: 'Some reviews mention service fees or tip pressure.',
  SCAM_WARNING: 'Some reviews use scam-like or rip-off wording.',
}

export const categoryTone = Object.fromEntries([
  ...positiveCategories.map((category) => [category, 'positive']),
  ...warningCategories.map((category) => [category, 'warning']),
])

export const categoryKeywords = {
  GOOD_FOOD: [
    'good food',
    'tasty',
    'delicious',
    'fresh',
    'amazing seafood',
    'amazing food',
    'great seafood',
    'great pizza',
    'good pasta',
    'traditional food',
    'excellent food',
    'excellent seafood',
  ],
  GOOD_SERVICE: [
    'friendly staff',
    'kind waiter',
    'helpful',
    'fast service',
    'welcoming',
    'professional staff',
    'polite waiter',
    'attentive service',
  ],
  GOOD_VALUE: [
    'fair price',
    'fair prices',
    'worth it',
    'good value',
    'affordable',
    'reasonable price',
    'reasonable prices',
    'great value',
    'value for money',
  ],
  AUTHENTIC_LOCAL: [
    'local',
    'authentic',
    'traditional',
    'not touristy',
    'family restaurant',
    'hidden gem',
    'local recommendation',
    'where locals go',
  ],
  BAD_FOOD: [
    'bad food',
    'cold food',
    'tasteless',
    'undercooked',
    'overcooked',
    'small portions',
    'small portion',
    'food poisoning',
    'not fresh',
    'poor quality',
  ],
  BAD_SERVICE: [
    'rude waiter',
    'rude',
    'unfriendly staff',
    'slow service',
    'ignored',
    'aggressive staff',
    'aggressive',
    'bad attitude',
    'terrible service',
    'waited too long',
  ],
  OVERPRICED: [
    'expensive',
    'overpriced',
    'too costly',
    'too expensive',
    'not worth the money',
    'not worth it',
    'price too high',
    'bad value',
    'tourist prices',
  ],
  TOURIST_TRAP: [
    'tourist trap',
    'avoid',
    'trap for tourists',
    'only for tourists',
    'low quality for high price',
    'stay away',
  ],
  HIDDEN_CHARGES: [
    'hidden fee',
    'extra charge',
    'charged extra',
    'unexpected charge',
    'charged more',
    'bill was higher',
    'cover charge',
    'bread charged',
    'water charged',
    'charged for bread',
    'charged for water',
  ],
  SERVICE_NOT_INCLUDED: [
    'service not included',
    'tip forced',
    'forced tip',
    'service charge',
    'waiter demanded tip',
    'demanded a tip',
    'mandatory tip',
    'charged for service',
    'service fee',
  ],
  SCAM_WARNING: [
    'scam',
    'cheated',
    'ripped off',
    'fraud',
    'dishonest',
    'charged without asking',
    'fake prices',
  ],
}
